/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class Bibliteca extends javax.swing.JFrame {

    /**
     * Creates new form Bibliteca
     */
    public Bibliteca() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldCodigoLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextFieldTitulo = new javax.swing.JTextField();
        ButtonNuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextFieldAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldBaseDatos = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        ButtonExaminar = new javax.swing.JButton();
        ButtonBorrar = new javax.swing.JButton();
        ButtonModificar = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Libreria Scocco");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Código de Libro");

        TextFieldCodigoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoLibroActionPerformed(evt);
            }
        });

        jLabel2.setText("Titulo");

        TextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTituloActionPerformed(evt);
            }
        });

        ButtonNuevo.setText("Nuevo");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });

        jLabel3.setText("Autor");

        TextFieldAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAutorActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        TextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPrecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Archivo:");

        TextFieldBaseDatos.setEditable(false);
        TextFieldBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBaseDatosActionPerformed(evt);
            }
        });

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        ButtonExaminar.setText("Examinar");
        ButtonExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExaminarActionPerformed(evt);
            }
        });

        ButtonBorrar.setText("Borrar");
        ButtonBorrar.setEnabled(false);
        ButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarActionPerformed(evt);
            }
        });

        ButtonModificar.setText("Modificar");
        ButtonModificar.setEnabled(false);
        ButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.setEnabled(false);
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldAutor)
                            .addComponent(TextFieldCodigoLibro)
                            .addComponent(TextFieldTitulo)
                            .addComponent(TextFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(ButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonExaminar)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(TextFieldTitulo))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonModificar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(ButtonCancelar)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCodigoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoLibroActionPerformed

    private void TextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTituloActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        
        Libro libro = new Libro();
        
        if(dao==null){
            JOptionPane.showMessageDialog(this, "Es necesario "
            + "abrir una Base de datos.");
            return;
        }
        try{
            libro.setCodigoLibro(TextFieldCodigoLibro.getText());
            libro.setTitulo(TextFieldTitulo.getText());
            libro.setAutor(TextFieldAutor.getText());
            libro.setPrecio(Integer.valueOf(TextFieldPrecio.getText()));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un precio valido");
            return;
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
                      
        try {
            dao.insertarLibro(libro); //no me permite genrar la excepciÃ³n 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return; 
        }
        JOptionPane.showMessageDialog(this, "El libro se agrego correctamente.");
        BorrarCampos();     
             
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void TextFieldAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAutorActionPerformed

    private void TextFieldBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBaseDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBaseDatosActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        String CodigoLibro;
        Libro libro;
        
        if(dao==null){
            JOptionPane.showMessageDialog(this, "Es necesario "
                + "abrir una Base de datos.");
            return;     
        }
        
        CodigoLibro = TextFieldCodigoLibro.getText();
        libro = dao.BuscarLibro(CodigoLibro);
        
        if(libro==null){
            JOptionPane.showMessageDialog(this, "No se econtro libro con ese codigo.");
            return;
        }
        
        TextFieldTitulo.setText(libro.getTitulo());
        TextFieldAutor.setText(libro.getAutor());
        TextFieldPrecio.setText(String.valueOf(libro.getPrecio()));
        desbloquearBotones();
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButtonExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExaminarActionPerformed
        JFileChooser selector = new JFileChooser();
        String url;
        int respuesta;
           
        respuesta = selector.showOpenDialog(this);
        
        if (respuesta==JFileChooser.CANCEL_OPTION) 
            return;
        
        url=selector.getSelectedFile().getAbsolutePath(); //trae ruta completa del nombre de archico AbsolutePath
        
        TextFieldBaseDatos.setText(url);
        //url= url.replace('\\', '/');
        
        try {
            dao = new DAOSQLite(url);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_ButtonExaminarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(dao!=null){
            try {
                dao.Desconectar();
            } catch (Exception ex) {
                Logger.getLogger(Bibliteca.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void ButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarActionPerformed
        String CodigoLibro;
        
        if(dao==null){
            JOptionPane.showMessageDialog(this, "Es necesario "
            + "abrir una Base de datos.");
            return;
        }
        
        CodigoLibro = TextFieldCodigoLibro.getText();
        
        try {
            dao.BorrarLibro(CodigoLibro);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this, "El libro se borro correctamente.");
        BorrarCampos();
        BloquearBotones();
        
    }//GEN-LAST:event_ButtonBorrarActionPerformed

    private void ButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarActionPerformed
        Libro libro = new Libro();
        
        if(dao==null){
            JOptionPane.showMessageDialog(this, "Es necesario "
            + "abrir una Base de datos.");
            return;
        }        
        
        try{
            libro.setCodigoLibro(TextFieldCodigoLibro.getText());
            libro.setTitulo(TextFieldTitulo.getText());
            libro.setAutor(TextFieldAutor.getText());
            libro.setPrecio(Integer.valueOf(TextFieldPrecio.getText()));            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un precio valido.");  
            return;
        
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        
        try {
            dao.ModificarLibro(libro);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
           
        }
        JOptionPane.showMessageDialog(this, "El Libro de modifico corrrectamente");
        BorrarCampos();
        BloquearBotones();

    }//GEN-LAST:event_ButtonModificarActionPerformed

    private void TextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPrecioActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        BorrarCampos();
        BloquearBotones();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void BorrarCampos(){
        TextFieldCodigoLibro.setText(null);
        TextFieldTitulo.setText(null);
        TextFieldAutor.setText(null);
        TextFieldPrecio.setText(null);

    }
    
    private void desbloquearBotones() {
        TextFieldCodigoLibro.setEditable(false);
        ButtonNuevo.setEnabled(false);
        ButtonBorrar.setEnabled(true);
        ButtonModificar.setEnabled(true);
        ButtonCancelar.setEnabled(true);
    }
    
    private void BloquearBotones() {
        TextFieldCodigoLibro.setEditable(true);
        ButtonNuevo.setEnabled(true);
        ButtonBorrar.setEnabled(false);
        ButtonModificar.setEnabled(false);
        ButtonCancelar.setEnabled(false);
    }
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bibliteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bibliteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bibliteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bibliteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bibliteca().setVisible(true);
            }
        });
    }
    
    private DAOSQLite dao = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBorrar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonExaminar;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JTextField TextFieldAutor;
    private javax.swing.JTextField TextFieldBaseDatos;
    private javax.swing.JTextField TextFieldCodigoLibro;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JTextField TextFieldTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    
    
}
